# Theming
general.import = [
    # uncomment the flavour you want below:
    # "~/.config/alacritty/catppuccin-latte.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml"
    # "~/.config/alacritty/catppuccin-macchiato.toml"
    "~/.config/alacritty/catppuccin-mocha.toml",
]

[window]
opacity = 0.7
blur = true

padding.x = 10
padding.y = 30

# dynamic_padding = true

decorations = "Transparent"
decorations_theme_variant = "Dark"

[font]
size = 14

normal.family = "MesloLGS NF"
bold.family = "MesloLGS NF"
italic.family = "MesloLGS NF"
bold_italic.family = "MesloLGS NF"

[env]
TERM = "alacritty"
